version: '3'

services:
  app:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app # Mount the entire project directory to /app
    env_file:
      - .env
    restart: unless-stopped
    container_name: ai-meeting-transcription
